name: Deploy to Production

on:
  push:
    branches: [ "production" ]

jobs:
  deploy_production:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python 3.11.4
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.4"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Create instance directory
      run: mkdir -p instance  
    # Assuming you'd still want to run migrations and seeds for production
    - name: Run database migrations
      run: python ./migrate.py up

    - name: Seed game and team data
      run: python ./scripts/seed_game_and_team_data.py
        
    - name: Run tests with pytest
      run: pytest

    - name: Create SSH key for Production
      run: |
        mkdir -p ~/.ssh/
        ssh-keyscan ${{ secrets.SERVER_HOSTNAME }} >> ~/.ssh/known_hosts
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

    - name: Deploy to Production Server
      if: success()
      run: |
        rsync -avz --exclude '__pycache__' --exclude 'venv' --exclude 'app.log' -e "ssh -v" ./ ${{ secrets.RSYNC_DEST_PROD }}
      env:
        DEPLOY_KEY: ${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}
